package tools

import (
	"briefly/internal/agent"
	"briefly/internal/core"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"google.golang.org/genai"
)

// RenderDigestTool renders the current digest draft as a curated newsletter markdown file.
type RenderDigestTool struct{}

func NewRenderDigestTool() *RenderDigestTool {
	return &RenderDigestTool{}
}

func (t *RenderDigestTool) Name() string { return "render_digest" }

func (t *RenderDigestTool) Description() string {
	return "Render the digest as a curated newsletter markdown file. Articles are grouped by topic with inline links and editorial summaries. Call this as the final step."
}

func (t *RenderDigestTool) Parameters() *genai.Schema {
	return &genai.Schema{
		Type: genai.TypeObject,
		Properties: map[string]*genai.Schema{
			"output_path": {
				Type:        genai.TypeString,
				Description: "Directory to write the markdown file to (default: digests)",
			},
		},
	}
}

func (t *RenderDigestTool) Execute(ctx context.Context, memory *agent.WorkingMemory, params map[string]any) (map[string]any, error) {
	digest := memory.GetDigestDraft()
	if digest == nil {
		return nil, fmt.Errorf("no digest draft to render")
	}

	outputDir := extractStringParam(params, "output_path", "digests")
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create output directory: %w", err)
	}

	dateStr := time.Now().Format("2006-01-02")
	outputPath := filepath.Join(outputDir, fmt.Sprintf("digest_%s.md", dateStr))

	articleIndex := memory.GetArticleIndex()
	triageScores := memory.GetTriageScores()
	markdown := renderCuratedNewsletter(digest, articleIndex, triageScores)

	if err := os.WriteFile(outputPath, []byte(markdown), 0644); err != nil {
		return nil, fmt.Errorf("failed to write digest file: %w", err)
	}

	wordCount := len(strings.Fields(markdown))

	return map[string]any{
		"file_path":     outputPath,
		"word_count":    wordCount,
		"article_count": len(articleIndex),
	}, nil
}

// renderCuratedNewsletter produces a curated link newsletter grouped by topic.
func renderCuratedNewsletter(digest *core.Digest, index []agent.ArticleIndexEntry, triageScores map[string]agent.TriageScore) string {
	var sb strings.Builder

	// Header
	title := digest.Title
	if title == "" {
		title = "GenAI Weekly"
	}
	sb.WriteString(fmt.Sprintf("# 🗞️ %s\n\n", title))
	sb.WriteString(fmt.Sprintf("*%d links this week | %s*\n\n",
		len(index), time.Now().Format("January 2, 2006")))

	// Week overview (TL;DR)
	if digest.TLDRSummary != "" {
		sb.WriteString(fmt.Sprintf("%s\n\n", digest.TLDRSummary))
	}

	sb.WriteString("---\n\n")

	// Group articles by topic
	topicOrder := agent.StableTopics()
	topicArticles := make(map[string][]agent.ArticleIndexEntry)
	var uncategorized []agent.ArticleIndexEntry

	for _, entry := range index {
		topicID := entry.TopicID
		if topicID == "" {
			if score, ok := triageScores[entry.ArticleID]; ok {
				topicID = score.TopicID
			}
		}
		if topicID == "" {
			uncategorized = append(uncategorized, entry)
		} else {
			topicArticles[topicID] = append(topicArticles[topicID], entry)
		}
	}

	// Render each topic that has articles
	for _, topic := range topicOrder {
		articles, ok := topicArticles[topic.ID]
		if !ok || len(articles) == 0 {
			continue
		}

		sb.WriteString(fmt.Sprintf("## %s\n\n", topic.Label))

		for _, entry := range articles {
			renderArticleEntry(&sb, entry, triageScores)
		}
	}

	// Render uncategorized articles under "Also Notable"
	if len(uncategorized) > 0 {
		sb.WriteString("## 📌 Also Notable\n\n")
		for _, entry := range uncategorized {
			renderArticleEntry(&sb, entry, triageScores)
		}
	}

	// Footer
	sb.WriteString(fmt.Sprintf("---\n*Generated by [Briefly](https://github.com/rcliao/briefly) on %s*\n",
		time.Now().Format("2006-01-02")))

	return sb.String()
}

// renderArticleEntry renders a single article as an inline link with editorial summary.
func renderArticleEntry(sb *strings.Builder, entry agent.ArticleIndexEntry, triageScores map[string]agent.TriageScore) {
	// Get editorial summary from triage scores or index
	editorial := entry.EditorialSummary
	if editorial == "" {
		if score, ok := triageScores[entry.ArticleID]; ok {
			editorial = score.EditorialSummary
		}
	}

	// Read time
	readTime := ""
	if entry.ReadMinutes > 0 {
		readTime = fmt.Sprintf(" · 📖 %d min", entry.ReadMinutes)
	}

	// Intent indicator
	intentIcon := ""
	intent := entry.ReaderIntent
	if intent == "" {
		if score, ok := triageScores[entry.ArticleID]; ok {
			intent = score.ReaderIntent
		}
	}
	switch intent {
	case "deep_dive":
		intentIcon = " · 🔬 Deep Dive"
	}

	// Bold title with read time
	sb.WriteString(fmt.Sprintf("- **%s**%s%s\n", entry.Title, readTime, intentIcon))

	// Editorial summary, then raw URL
	if editorial != "" {
		sb.WriteString(fmt.Sprintf("  %s\n", editorial))
	}
	sb.WriteString(fmt.Sprintf("  %s\n", entry.URL))

	sb.WriteString("\n")
}
